### PR TITLE
Notebooks TOML

### PR DESCRIPTION
**Pull request by arnavs**
I believe this is all that's required to update the notebooks to the new `InstantiateFromURL` scheme going forward. tl;dr Add `SimpleDifferentialOperators.jl` to the `docs/examples/{Project, Manifest}.toml`, and keep track of the versions using the Manifest there.

Will merge this once the new release of Instantiate gets approved, and I can test it in full.

### CODE REVIEW

**Comment by arnavs** [comment]
The one drawback of this kind of approach (@jlperla) is that it makes it impossible for the `dev` notebooks to use the actual `master` branch (because they're relying on TOML to be reproducible, but `master` isn't a tagged version.)

Maybe the solution is to stop showing those docs, once this package is in a somewhat stable state.

**Comment by jlperla** [comment]
But isn't that why you publish it with the version tag on the notebook?

**Comment by arnavs** [comment]
Right. To be clear, this approach will work for all of our `stable` docs (i.e., the static tags.) But it won't work for `master`, because it's impossible to get that cleanly into `Manifest.toml` without a tagged release.

**Comment by arnavs** [comment]
This discussion is complicated by the fact that there's the `master` set of TOML files (which we can always pull), and the `master` state of the actual SDO package (which we can't include in a Manifest file.)

Anyways, we can talk more when we meet this morning.

**Comment by jlperla** [comment]
@arnavs  What is the status of this?  Should we merge and test prior to a new tag?

**Pull request merged**
